### ISSUE TITLE
PyPi Installation of the Package fails

### ISSUE THREAD

**Issue by xpostudio4** [fusionbox/django-widgy-blog#32]
While installing the PyPi version of widgy-blog I receive the following error, locally I'm able to install it with a sudo or creating the folder of reference first, but it is a mess when deploying. It's there any way to fix this?.

```
(widgy-blog)➜  widgy-blog  pip install widgy-blog
Collecting widgy-blog
  Using cached widgy-blog-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/14/z5sy6wbj7yl5mc8y6b3v11j80000gn/T/pip-build-qx8Z_o/widgy-blog/setup.py", line 24, in <module>
        long_description='\n\n'.join([read('README.rst'), read('CHANGES.rst')]),
      File "/private/var/folders/14/z5sy6wbj7yl5mc8y6b3v11j80000gn/T/pip-build-qx8Z_o/widgy-blog/setup.py", line 15, in read
        with open(get_absolutepath(fname), 'r') as f:
    IOError: [Errno 2] No such file or directory: '/private/var/folders/14/z5sy6wbj7yl5mc8y6b3v11j80000gn/T/pip-build-qx8Z_o/widgy-blog/CHANGES.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/14/z5sy6wbj7yl5mc8y6b3v11j80000gn/T/pip-build-qx8Z_o/widgy-blog
```

PD: I was able to installed on the server with `-e git+https://github.com/fusionbox/django-widgy-blog@3698fb9d7e126b125987169109a3b312ee1b82e0#egg=widgy-blog
` in case it helps

**Comment by jxcl** [comment]
Hi Leo!

Thanks for this report. We've released `django-widgy-blog` 0.2.0, which should work.
